services:
  admin-panel:
    build: ./admin-panel
    ports:
      - "8080:8080"
    depends_on:
      - invoice-service
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  invoice-service:
    build:
      context: ./invoice-service
      dockerfile: Dockerfile
    container_name: invoice-service
    env_file:
      - ./invoice-service/.env
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      
  email-sender-service:
    build:
      context: ./email-sender-service
    container_name: email-sender-service
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - ./email-sender-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
